DROP TABLE IF EXISTS medecin ;
CREATE TABLE medecin (id INT  AUTO_INCREMENT NOT NULL,
num_tel VARCHAR(10),
nom VARCHAR(20),
prenom VARCHAR(20),
adresse VARCHAR(50),
commune VARCHAR(20),
specialite VARCHAR(20),
ouverture INT,
fermeture INT,
gps VARCHAR(100),
mdp VARCHAR(20),
initial TINYINT(1),
PRIMARY KEY (id)) ENGINE=InnoDB;


DROP TABLE IF EXISTS patient ;
CREATE TABLE patient (nss VARCHAR(10) NOT NULL,
nom VARCHAR(20),
prenom VARCHAR(20),
num_tel VARCHAR(10),
mdp VARCHAR(20),
adresse VARCHAR(50),
initial TINYINT(1),
PRIMARY KEY (nss) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS traitant ;
CREATE TABLE traitant (id_med INT NOT NULL,
nss_pt VARCHAR(10),
PRIMARY KEY (id_med, nss_pt),
FOREIGN KEY (id_med) REFERENCES medecin (id)  ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (nss_pt) REFERENCES patient (nss)  ON DELETE CASCADE ON UPDATE CASCADE
 ) ENGINE=InnoDB;

DROP TABLE IF EXISTS rdv ;
CREATE TABLE rdv (id INT  AUTO_INCREMENT NOT NULL,
date_rdv DATETIME,
id_med INT,
nss_pt VARCHAR(10),
PRIMARY KEY (id),
FOREIGN KEY (id_med) REFERENCES medecin (id)  ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (nss_pt) REFERENCES patient (nss)  ON DELETE CASCADE ON UPDATE CASCADE
 ) ENGINE=InnoDB;

DROP TABLE IF EXISTS traitement ;
CREATE TABLE traitement (id INT  AUTO_INCREMENT NOT NULL,
duree INT,
id_med INT,
id_rdv INT,
nss_pt VARCHAR(10),
PRIMARY KEY (id),
FOREIGN KEY (id_med) REFERENCES medecin (id)  ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (nss_pt) REFERENCES patient (nss)  ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (id_rdv) REFERENCES rdv (id)  ON DELETE CASCADE ON UPDATE CASCADE
 ) ENGINE=InnoDB;

DROP TABLE IF EXISTS medicament ;
CREATE TABLE medicament (id INT  AUTO_INCREMENT NOT NULL,
designation VARCHAR(20),
PRIMARY KEY (id) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS ligne_trt ;
CREATE TABLE ligne_trt (id INT  AUTO_INCREMENT NOT NULL,
id_trt INT,
id_mdcm INT,
heure INT,
PRIMARY KEY (id),
FOREIGN KEY (id_trt) REFERENCES traitement (id)  ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (id_mdcm) REFERENCES medicament (id)  ON DELETE CASCADE ON UPDATE CASCADE
 ) ENGINE=InnoDB;
